change (fix) maven-compiler-plugin configuartion
Try to fix the error: Failed to execute goal
org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile
(default-compile) on project swat-dp-ant-tools: Fatal error compiling:
error: invalid target release: 14

* use release property instead of source and target
* use java 11 instead of 14